### ISSUE TITLE
error while executing npm run production

### ISSUE THREAD

**Issue by ashachy** [viralsolani/laravel-adminpanel#211]
Whoops! We had trouble minifying "public/js/backend-custom.js". Perhaps you need to use mix.babel() instead?

**Comment by bvipul** [comment]
What npm version are you using? 
I have used 5.4.2(node 8.8.1) and 5.7.1(node 9.7.1), and in both it is working perfectly.
Please provide your rig, so we can debug. 
Thanks.

**Comment by bvipul** [comment]
Since there is no response of this thread, I am closing this issue.

**Comment by minutmorph** [comment]
Hi, getting the same issue. Using npm 6.1.0. Thanks

**Comment by minutmorph** [comment]
Sorry, forgot to mention other (possible) relevant specs: Node v10.2.1 on Mac OSX. Here is the output from terminal:

$ npm run prod

> @ prod /Users/user/projects/laravel56test/app
> npm run production


> @ production /Users/user/projects/laravel56test/app
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 95% emitting                                                                         

 DONE  Compiled successfully in 118057ms                                                                                                                                                              21:20:20

Whoops! We had trouble minifying "public/js/backend-custom.js". Perhaps you need to use mix.babel() instead?

/Users/user/projects/laravel56test/app/node_modules/laravel-mix/src/webpackPlugins/CustomTasksPlugin.js:64
                    throw e;
                    ^
SyntaxError: Unexpected token: punc (()
    at JS_Parse_Error.get (eval at <anonymous> (/Users/user/projects/laravel56test/app/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2018-05-31T20_20_22_073Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ prod: `npm run production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/user/.npm/_logs/2018-05-31T20_20_22_109Z-debug.log

===============================================
===============================================

And this is the log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'prod' ]
2 info using npm@5.6.0
3 info using node@v10.2.1
4 verbose run-script [ 'preprod', 'prod', 'postprod' ]
5 info lifecycle @~preprod: @
6 info lifecycle @~prod: @
7 verbose lifecycle @~prod: unsafe-perm in lifecycle true
8 verbose lifecycle @~prod: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/user/projects/laravel56test/app/node_modules/.bin:/usr/local/opt/m4/bin:/Applications/MAMP/Library/bin:/Applications/MAMP/bin/php/php7.2.1/bin:/Users/user/.composer/vendor/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle @~prod: CWD: /Users/user/projects/laravel56test/app
10 silly lifecycle @~prod: Args: [ '-c', 'npm run production' ]
11 silly lifecycle @~prod: Returned: code: 1  signal: null
12 info lifecycle @~prod: Failed to exec prod script
13 verbose stack Error: @ prod: `npm run production`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:961:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
14 verbose pkgid @
15 verbose cwd /Users/user/projects/laravel56test/app
16 verbose Darwin 17.5.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "prod"
18 verbose node v10.2.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error @ prod: `npm run production`
22 error Exit status 1
23 error Failed at the @ prod script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

============================================================
============================================================

This only happens when running production.

Otherwise, this package is great! 

Thanks again.
