### ISSUE TITLE
Issue while creating a new data in repository

### ISSUE THREAD

**Issue by bibek54** [viralsolani/laravel-adminpanel#234]
It was 
`$xyz = self::MODEL;
        $xyz = new $xyz();
        if ($xyz->save($input)) {
            return true;
        }`
in the create method of repository while it is supposed to be
`$xyz = self::MODEL;
        $xyz = new $xyz($input);
        if ($xyz->save()) {
            return true;
        }`

**Comment by viralsolani** [comment]
Can you please show us the error message or let us know exact location?

**Comment by bvipul** [comment]
@viralsolani @bibek54 I know, it is in Repository file generated by the module generator. And @bibek54 has pointed out correctly that we should not use `save($input)`. Thanks. I will solve that in generator. And that will be in our next release. Or @bibek54 if you want to contribute to the [generator](https://www.github.com/bvipul/generator) repo, you can add a PR their.

**Comment by bvipul** [comment]
@bibek54 @viralsolani turns out it in generator we don't use save() method, so @bibek54 it will be useful if you can point us to the right file.

**Comment by bibek54** [comment]
The place where the issue is being created is the repository file for the created model in create method.

**Comment by bvipul** [comment]
@bibek54 I am sorry, but I am not able to find any repository file which has `save($input)`. Can you please give me the name of the file?

**Comment by bvipul** [comment]
@bibek54 I found the issue where you found this, as we had published the package's view files and I have updated the files but those published views were not updated. Thanks for pointing out. I have removed that folder from resources/views/vendor/generator. If you need to modify any view files of module generator you can again just run: `php artisan vendor:publish`. This issue is resolved in my latest commit.
