### ISSUE TITLE
Menu edit redirect to blog edit page

### ISSUE THREAD

**Issue by umair321** [viralsolani/laravel-adminpanel#242]
Menu edit redirect to blog edit page in latest repo.

**Solution**

I have replace MenuController in backend folder with previous one then it is working fine

**Comment by vrkansagara** [comment]
@umair321 Can you provide more details on this issue.

**Comment by umair321** [comment]
![ggtu](https://user-images.githubusercontent.com/7020208/42366196-0b338afc-811a-11e8-8680-c8e659b3ef7d.png)
I cloned repo and checked menu was not working well so I replaced MenuController with previous downloaded repo which I downloaded 2 months ago for laravel 5.5

**Comment by vrkansagara** [comment]
@umair321 We are look into this. and let you know once fix.

**Comment by bvipul** [comment]
@umair321 I am going to close this issue, as this can not happen, I have checked the master branch's code and we have below code to show edit button and delete button:
```
public function getActionButtonsAttribute()
    {
        return '<div class="btn-group action-btn">
                    '.$this->getEditButtonAttribute('edit-menu', 'admin.menus.edit').'
                    '.$this->getDeleteButtonAttribute('delete-menu', 'admin.menus.destroy').'
                </div>';
    }
```
please look at the file at this location : App\Models\Menu\Traits\Attribute\MenuAttribute.php and tell us what's wrong, because I can not find a problem their.

You can always reopen this issue, if it persists.
