### ISSUE TITLE
Role Management is not working

### ISSUE THREAD

**Issue by mehadihasan** [viralsolani/laravel-adminpanel#256]
Associated Permissions is not working for "Executive" Role or any new role. In Role Management if I add or remove any Associated Permissions nothing is changing.

**Comment by bvipul** [comment]
@mehadihasan You will have to understand, the role's associated permissions are not attached to users directly. The roles are just a way to group the permissions and assign users with that role. Now, if you add/update a permission from role's associated permissions, it should not change all the users with that role, because you might have given any particular user a different set of permission other that its role. If we change all the users's permission of that changed role, it will affect in individual permission conflicting with role's permissions.

This is totally a concern. If anyone can suggest something. It will really be appreciated.

**Comment by mehadihasan** [comment]
Okay! This is one kind of Bug I think.
I will work on it. If I can solve this problem, I will share the code.
Or if anyone already have solved this problem, they can share the code also :)

**Comment by Malwindersingjh** [comment]
I have user,role and permission issue. When I revoke page create permissions from a role (e.g. executive role)  then it still allowing that user to create a page. Same when I create a new permission and assign to a role then it do not work.

Is there any permission cache needed to reset ?

**Comment by bvipul** [comment]
There is no issue in going either way, I am just saying, only one of them needs to be applied at any time....
