### ISSUE TITLE
how to run without php artisan serve

### ISSUE THREAD

**Issue by khushub** [viralsolani/laravel-adminpanel#609]
i want to run this project on localhost without php artisan serve. so please provide htaccess file for that

**Comment by krguptaa** [comment]
Hello Khushub,

1. 
Rename the "server.php" file in root directory, in "index.php"
Move your .htaccess from public folder to root directory
Make your directory accessible to Apache2 (set correct file/folder permissions).
2.
Consider using Apache Virtual Hosts (pointing the virtual host to the /public Laravel folder) instead of renaming server.php to index.php because by doing this you will need to prefix "public/" when you use the Laravel's asset() function in your views.
